import { STANDARD_STATES } from '@cards-ts/core';

export const GameStates = {
    ...STANDARD_STATES,

    START_ROUND: 'START_ROUND',
    WAIT_FOR_TURN_PLAYER_WANT: 'WAIT_FOR_TURN_PLAYER_WANT',
    HANDLE_TURN_PLAYER_WANT: 'HANDLE_TURN_PLAYER_WANT',

    WAIT_FOR_PLAYER_WANT: 'WAIT_FOR_PLAYER_WANT',
    HANDLE_PLAYER_WANT: 'HANDLE_PLAYER_WANT',

    HANDLE_NO_PLAYER_WANT: 'HANDLE_NO_PLAYER_WANT',

    START_TURN: 'START_TURN',
    WAIT_FOR_TURN: 'WAIT_FOR_TURN',
    HANDLE_TURN: 'HANDLE_TURN',

    END_ROUND: 'END_ROUND',
} as const;
