name: release
on:
  push:
    branches:
      - master

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
        with:
          # Changsets action requires full history
          fetch-depth: 0

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.27.1
          run_install: true

      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install Dependencies
        run: pnpm i

      - name: Build
        run: pnpm buildall

      - name: Changesets PR / Publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm changeset version
          publish: pnpm changeset publish
          title: Version packages
          commit: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Changesets Snapshot
        if: steps.changesets.outputs.published != 'true'
        run: |
          pnpm changeset version --snapshot
          pnpm changeset publish --tag --no-git-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        
      - name: Documentation
        if: steps.changesets.outputs.published == 'true'
        run: pnpm doc

      - name: Commit Files
        if: steps.changesets.outputs.published == 'true'
        run: |
          git checkout -b gh-pages
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          touch docs/.nojekyll
          git add -f docs
          git commit -m "Update docs"

      - name: Push Changes
        if: steps.changesets.outputs.published == 'true'
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}